name: yoddhafoundation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_easyloading: ^3.0.3
  dio: ^4.0.0
  sqflite: ^2.0.0+4
  hexcolor: ^2.0.5
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  connectivity: ^3.0.6
  device_info: ^2.0.2
  app_tracking_transparency: ^2.0.1
  image_picker: ^0.8.4+2
  pattern_formatter: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
